// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'chapters/module-1-ros2'}],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'chapters/module-2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'chapters/module-3-ai-robot-brain'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'chapters/module-4-vision-language-action'}],
    },
  ],
};

export default sidebars;
