/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro', // This keeps your Introduction at the top
    {
      type: 'category',
      label: 'Textbook Modules',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'chapters', // This ONLY looks inside the chapters folder
        },
      ],
    },
  ],
};

export default sidebars;
