/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Textbook Content',
      items: [
        {
          type: 'autogenerated',
          dirName: '.', // This finds intro.md and the chapters folder automatically
        },
      ],
    },
  ],
};

export default sidebars;
