/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro', // Make sure frontend_book/docs/intro.md exists
    {
      type: 'category',
      label: 'Modules',
      items: [{type: 'autogenerated', dirName: 'chapters'}], 
    },
  ],
};

export default sidebars;
